#!/usr/bin/env bash
# Workflow for the HYBRID VSjet measurement (ParticleNet / UParT), correlated-TES variant.
# Sibling of run_workflow_zmm_corrTES.sh (DeepTau). Select the tagger with TAGGER below;
# config, WP list and separate I/O trees follow from it. VSjet = PNet/UParT raw-score WP,
# VSe/VSmu = DeepTau (hybrid); decay-mode binning = 6 bins {0,1,2,10,11,rest}.
#
# Prereq: inputs generated by run_inputs_pnet.sh (same TAGGER) into input_pt_less_region_<tagger>/.
#
# NOTE: the fit scripts currently embed extratag "_DeepTau" in output filenames (TAG below).
# That is cosmetic — outputs live in the separate _<tagger> trees. The deployed SF *label*
# (correctionlib id) is set in createroot_TES.py and still needs de-hardcoding to the tagger.

TAGGER="pnet"          # pnet | upart

case "$TAGGER" in
  pnet)  CONFIG_TT="TauES_ID/config/config_coarse_PNet.yml";  SUFFIX="pnet"  ;;
  upart) CONFIG_TT="TauES_ID/config/config_coarse_UParT.yml"; SUFFIX="upart" ;;
  *) echo "unknown TAGGER=$TAGGER (use pnet|upart)"; exit 1 ;;
esac

J_VALUES=("VVTight") # "Loose" "Medium" "Tight" "VTight"   # PNet/UParT VSjet WPs (raw-score)
E_VALUES=("VVLoose")                                       # DeepTau VSe WP: mt/tt convention = VVLooseVSe (VSmu=Tight via baseline)
YEARS=("2024") # "2025"
DMS=("DM0" "DM1" "DM2" "DM10")                           # 4 PNet/UParT CP decay-mode bins {pi,rho,a1-1pr,a1-3pr}
DMS_CSV=$(IFS=,; echo "${DMS[*]}")                       # for plotters that take --dms
TAG="_DeepTau"                                           # embedded fit tag (see NOTE above)
CONFIG_MM="TauES/config/FitSetup_mumu.yml"

INPUT_ROOT="input_pt_less_region_${SUFFIX}"                 # produced by run_inputs_pnet.sh
# NOTE: the fit derives its output tree from the input path as
# input_pt_less_region_<tag> -> output_pt_less_region_corrTES_<tag>, so the trees below
# MUST carry the _corrTES_ infix to match what the fit/harvest actually write.
OUTPUT_ROOT="output_pt_less_region_corrTES_${SUFFIX}"
PLOTS_ROOT="plots_pt_less_region_corrTES_${SUFFIX}"
PULL_TOOL="${CMSSW_BASE}/src/HiggsAnalysis/CombinedLimit/test/diffNuisances.py"

for YEAR in "${YEARS[@]}"; do
  for JET_WP in "${J_VALUES[@]}"; do
    for ELE_WP in "${E_VALUES[@]}"; do
      echo "==============================================================="
      echo "=== [${TAGGER}] year=${YEAR} VSjet=${JET_WP} VSe(DeepTau)=${ELE_WP} ==="
      echo "==============================================================="

      BASE_INPUT="${INPUT_ROOT}/againstjet_${JET_WP}/againstelectron_${ELE_WP}"
      BASE_OUTPUT="${OUTPUT_ROOT}/againstjet_${JET_WP}/againstelectron_${ELE_WP}"
      BASE_POSTFIT="${OUTPUT_ROOT/output/postfit}/againstjet_${JET_WP}/againstelectron_${ELE_WP}"
      BASE_PLOTS="${PLOTS_ROOT}/againstjet_${JET_WP}/againstelectron_${ELE_WP}"

      echo "=== Step 1: Zmm CR datacard + per-DM MultiDimFit ==="
      python3 TauES_ID/harvestDatacards_zmm.py -y $YEAR -c $CONFIG_MM -i ${BASE_INPUT}/ -o ${BASE_OUTPUT}/$YEAR/
      # python3 TauES_ID/makecombinedfitTES_SF_corrTES.py -y $YEAR -c $CONFIG_TT -i ${BASE_INPUT}/ \
      #   --input_file ${BASE_INPUT}/ztt_mt_tes_m_vis.inputs-$YEAR-13TeV_mutau.root \
      #   -o 3 --mumu_datacard_file ${BASE_OUTPUT}/$YEAR/ztt_mm_m_vis-baseline_mumu-$YEAR-13TeV.txt \
      #   2>&1 | tee step1_multidimfit_${SUFFIX}_${YEAR}_${JET_WP}_${ELE_WP}.log

      echo "=== Step 2: FitDiagnostics + PostFit (per-DM) ==="
      python3 TauES_ID/makecombinedfitTES_SF_postfit_corrTES.py -y $YEAR -c $CONFIG_TT \
        --indir ${BASE_OUTPUT}/ -o 3 \
        --mumu_input_file ${BASE_OUTPUT}/$YEAR/ztt_mm_m_vis-baseline_mumu-$YEAR-13TeV.txt \
        -cmm $CONFIG_MM --jet_wp ${JET_WP} --ele_wp ${ELE_WP} \
        2>&1 | tee step2_postfit_${SUFFIX}_${YEAR}_${JET_WP}_${ELE_WP}.log

      echo "=== Step 2b: Nuisance pull plots (per DM) ==="
      PULLDIR="${BASE_PLOTS}/${YEAR}/pulls"
      mkdir -p "${PULLDIR}"
      for DM in "${DMS[@]}"; do
        FD="${BASE_POSTFIT}/${YEAR}/fitDiagnostics.mt_m_vis-${DM}_mutau${TAG}-${YEAR}-13TeV.root"
        if [ ! -f "${FD}" ]; then echo "  [pulls] missing ${FD} — skip ${DM}"; continue; fi
        PULLTXT="${PULLDIR}/pulls_${JET_WP}_${ELE_WP}_${DM}.txt"
        python3 "${PULL_TOOL}" --poi tes_${DM} --vtol=0.1 "${FD}" 2>/dev/null | sed 's/[!,]/ /g' | tail -n +4 > "${PULLTXT}"
        python3 scripts/plot_pulls.py -f "${PULLTXT}" -o "${PULLDIR}/pulls_${JET_WP}_${ELE_WP}_${DM}" -t "${JET_WP}/${ELE_WP} ${DM}"
      done

      echo "=== Step 3: Plots ==="
      python3 python/plot/runpostfit.py --variant corr --tagger ${SUFFIX} -c $CONFIG_TT -j ${JET_WP} -e ${ELE_WP} -y $YEAR --include-cr \
        2>&1 | tee step3_plots_${SUFFIX}_${YEAR}_${JET_WP}_${ELE_WP}.log
      python3 pre_post_plot_combiner.py --variant corr --tagger ${SUFFIX} --scan_dir ${BASE_PLOTS}/$YEAR/ --jet_wp ${JET_WP} --ele_wp ${ELE_WP}
      python3 plot_measurements.py --variant corr --tagger ${SUFFIX} --jet_wp ${JET_WP} --ele_wp ${ELE_WP} --year $YEAR

      echo "=== Step 4: Correction file generation ==="
      python3 createroot_TES.py --variant corr --tagger ${SUFFIX} -c $CONFIG_TT -j ${JET_WP} -e ${ELE_WP} -f root -y $YEAR
      python3 createroot_TES.py --variant corr --tagger ${SUFFIX} -c $CONFIG_TT -j ${JET_WP} -e ${ELE_WP} -f json -y $YEAR

      echo "=== [${TAGGER}] done: year=${YEAR} Jet=${JET_WP} Ele=${ELE_WP} ==="
      echo
    done
  done

  echo "=== Scan grids per WP combo (${SUFFIX}, ${YEAR}) ==="
  python3 make_scan_grid.py --variant corr --root ${PLOTS_ROOT} --dms ${DMS_CSV}
  python3 make_measurements_grid.py

  echo "=== Merging JSON correction files (${SUFFIX}, ${YEAR}) ==="
  python3 merge_tau_jsons.py --variant corr --type both -c $CONFIG_TT -o tau_sf/TauCorrections_${YEAR}_${SUFFIX}.json

  echo "=== 1D profile NLLs (${SUFFIX}, ${YEAR}) ==="
  python3 plot1D_NLL_profiles.py --variant corr --year $YEAR --dms ${DMS_CSV} --indir ${OUTPUT_ROOT} --outdir ${PLOTS_ROOT}

  echo "=== Building combined TauEnergy_SF + TauID_SF (${SUFFIX}, ${YEAR}) ==="
  python3 make_tid_2025.py --variant corr -y $YEAR -c $CONFIG_TT
done

echo "All ${TAGGER} workflows completed!"
